[package]
before_cmds = [
	"mkdir -p bin/x86_64 bin/armv7 bin/aarch64",
	"cp $(nix build .#armv7-unknown-linux-musleabihf --print-out-paths --no-link)/bin/notify_push bin/armv7",
	"cp $(nix build .#aarch64-unknown-linux-musl --print-out-paths --no-link)/bin/notify_push bin/aarch64",
	"cp $(nix build .#x86_64-unknown-linux-musl --print-out-paths --no-link)/bin/notify_push bin/x86_64",
]
